kind = "mobile"
previewPath = "/nova-mobile/"
title = "Nova Anime Mobile"
version = "1.0.0"
id = "artifacts/nova-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/nova-mobile/" ]
localPort = 23209

[services.development]
run = "pnpm --filter @workspace/nova-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nova-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/nova-mobile", "run", "serve" ]

[services.env]
PORT = "23209"
BASE_PATH = "/nova-mobile/"
